# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
